---
- name: Ensure the I2C interface is enabled in the configuration
  become: true
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^#dtparam=i2c_arm=.*'
    line: dtparam=i2c_arm=on

- name: Ensure the I2C kernel module is configured to be loaded at boot time
  become: true
  ansible.builtin.lineinfile:
    path: /etc/modules
    create: true
    mode: 0644
    line: i2c-dev

- name: Set device tree parameters for I2C
  become: true
  ansible.builtin.command:
    cmd: /usr/bin/dtparam i2c_arm=on
  changed_when: always

- name: Load the I2C kernel module
  become: true
  community.general.modprobe:
    name: i2c-dev
...
